export enum TAB_NAMES {
  PROPERTIES = 'Properties',
  TEAM = 'Team',
  MEDIA = 'Media',
  PROCEDURES = 'Procedures',
  PROPERTY_PROCEDURES = 'Property Procedures',
  BUILDINGS = 'Buildings',
  TENANT_SPACES = 'Tenant Spaces',
  ALARMS = 'Alarms',
  CALL_LIST = 'Call List',
  COMMAND_CENTERS = 'Command Centers',
  COMMUNITY_RESOURCES = 'Community Resources',
  EVACUATIONS = 'Evacuations',
  HAZ_MAT = 'Hazardous Materials',
  INS_POLICIES = 'Insurance Policies',
  RELOCATIONS = 'Relocations',
  SHELTER_IN_PLACE = 'Shelter In Place',
  SHUTOFFS = 'Shut-Offs',
  VENDOR_CONTACTS = 'Vendor Contacts',
  MASTER_POLICIES = 'Master Policy Details',
  FAQ = 'Secure Guides',
}
